version: 2

sources: 
  - name: raw_data
    schema: gz_raw_data
    tables: 
      - name: sales
        identifier: raw_gz_sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
      - name: ship
        identifier: raw_gz_ship
      - name: product
        identifier: raw_gz_product
    
